package com.proj.userservice.models;

import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import lombok.Getter;
import lombok.Setter;

/*The @MappedSuperclass annotation in Java's JPA (Java Persistence API) is used to define a base class that can share its mapping information with its subclasses. This base class is not itself an entity and does not have a corresponding table in the database. Instead, the mapping information defined in the base class is inherited by its subclasses, which are entities.*/
@MappedSuperclass
@Getter
@Setter
public class BaseModel {
    @Id
    /* @GeneratedValue: Indicates that the value of the primary key should be automatically generated by the persistence provider (e.g., Hibernate).
       strategy = GenerationType.IDENTITY: Specifies that the database will handle the generation of the primary key value, usually through an auto-increment column.*/
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long id;
}
